version: "3.9"
services:
  manager_container:
    image: "docker:latest"
    container_name: manager_container
    privileged: true
    networks:
      - harvy
    ports:
      - "1000:1000"
      - "9000:9000"
    tty: true
  worker_one_container:
    image: "docker:latest"
    container_name: worker_one_container
    tty: true
    privileged: true
    networks:
      - harvy
  worker_two_container:
    image: "docker:latest"
    container_name: worker_two_container
    tty: true
    privileged: true
    networks:
      - harvy
  web_container:
    build:
      dockerfile: Docker/Dockerfile
    container_name: web_container
    tty: true
    privileged: true
    ports:
      - "5000:5000"
    networks:
      - harvy

networks:
  harvy: