version: "3.9"
services:
  worker_one_container:
    build:
      dockerfile: Docker/DockerFile_Worker
    container_name: worker_one_container
    tty: true
    privileged: true
    networks:
      - harvy
  worker_two_container:
    build:
      dockerfile: Docker/DockerFile_Worker
    container_name: worker_two_container
    tty: true
    privileged: true
    networks:
      - harvy
  web_container1:
    build:
      dockerfile: Docker/DockerFile_ShowMultipleServices
    container_name: web_container1
    tty: true
    privileged: true
    ports:
      - "5000:5000"
    networks:
      - harvy
  web_container2:
    build:
      dockerfile: Docker/DockerFile_ShowOneService
    container_name: web_container2
    privileged: true
    ports:
      - "90:3000"
      - "80:80"
    networks:
      - harvy

networks:
  harvy: