version: "3.9"
services:
  worker_one_container:
    build:
      dockerfile: Docker/DockerFile_Worker
    container_name: worker_one_container
    tty: true
    privileged: true
    networks:
      - harvy
  worker_two_container:
    build:
      dockerfile: Docker/DockerFile_Worker
    container_name: worker_two_container
    tty: true
    privileged: true
    networks:
      - harvy
  multiple_service_container:
    build:
      dockerfile: Docker/DockerFile_ShowMultipleServices
    container_name: multiple_service
    tty: true
    privileged: true
    ports:
      - "5000:5000"
    networks:
      - harvy
  one_service:
    build:
      dockerfile: Docker/DockerFile_ShowOneService
    container_name: one_service
    privileged: true
    ports:
      - "4000:4000"
    networks:
      - harvy

networks:
  harvy: